import { MenuItem } from "../components/Menu";

export const panAsianMenu: MenuItem[] = [
  // Japan
  {
    id: "pa-jp-ap-1",
    name: "Edamame",
    description: "Steamed & Salted Soybeans",
    price: 6,
    category: "japan",
    dietary: ["vegetarian", "gluten-free"],
  },
  {
    id: "pa-jp-ap-2",
    name: "Agedashi Tofu",
    description: "Lightly Fried Tofu in Dashi Broth",
    price: 8,
    category: "japan",
    dietary: ["vegetarian"],
  },
  {
    id: "pa-jp-ap-3",
    name: "Gyoza",
    description: "Pan-Fried Pork or Vegetable Dumplings",
    price: 9,
    category: "japan",
    dietary: [],
  },
  {
    id: "pa-jp-mc-1",
    name: "Chicken Teriyaki",
    description: "Grilled chicken with a sweet and savory teriyaki glaze",
    price: 18,
    category: "japan",
    dietary: [],
  },

  // China
  {
    id: "pa-cn-ap-1",
    name: "Siu Mai",
    description: "Pork and Shrimp Dumplings",
    price: 10,
    category: "china",
    dietary: [],
  },
  {
    id: "pa-cn-ap-2",
    name: "Har Gow",
    description: "Shrimp Dumplings",
    price: 11,
    category: "china",
    dietary: [],
  },
  {
    id: "pa-cn-mc-1",
    name: "Peking Duck",
    description: "with Pancakes, Scallions, and Hoisin Sauce",
    price: 45,
    category: "china",
    dietary: [],
    featured: true,
  },
  {
    id: "pa-cn-mc-2",
    name: "Kung Pao Chicken",
    description: "Spicy stir-fried chicken with peanuts, vegetables, and chili peppers",
    price: 19,
    category: "china",
    dietary: [],
    spiceLevel: 2,
  },

  // Korea
  {
    id: "pa-kr-ap-1",
    name: "Kimchi Jeon",
    description: "Kimchi Pancake",
    price: 12,
    category: "korea",
    dietary: ["vegetarian"],
    spiceLevel: 1,
  },
  {
    id: "pa-kr-bbq-1",
    name: "Bulgogi",
    description: "Marinated Beef, grilled at the table",
    price: 25,
    category: "korea",
    dietary: [],
  },
  {
    id: "pa-kr-mc-1",
    name: "Bibimbap",
    description: "Mixed Rice with Vegetables, Meat, and Egg",
    price: 20,
    category: "korea",
    dietary: [],
  },

  // Thailand
  {
    id: "pa-th-ap-1",
    name: "Satay Gai",
    description: "Chicken Satay with Peanut Sauce",
    price: 13,
    category: "thailand",
    dietary: [],
  },
  {
    id: "pa-th-sp-1",
    name: "Tom Yum Goong",
    description: "Spicy Shrimp Soup",
    price: 10,
    category: "thailand",
    dietary: ["gluten-free"],
    spiceLevel: 3,
  },
  {
    id: "pa-th-mc-1",
    name: "Pad Thai",
    description: "Stir-fried Rice Noodles with Shrimp or Chicken",
    price: 18,
    category: "thailand",
    dietary: [],
  },

  // Vietnam
  {
    id: "pa-vn-ap-1",
    name: "Goi Cuon",
    description: "Fresh Spring Rolls with Shrimp and Pork",
    price: 9,
    category: "vietnam",
    dietary: ["gluten-free"],
  },
  {
    id: "pa-vn-sp-1",
    name: "Pho Bo",
    description: "Beef Noodle Soup",
    price: 16,
    category: "vietnam",
    dietary: [],
  },
  {
    id: "pa-vn-sw-1",
    name: "Banh Mi",
    description: "Vietnamese Baguette with Grilled Pork, Pâté, and Vegetables",
    price: 14,
    category: "vietnam",
    dietary: [],
  },

  // India
  {
    id: "pa-in-ap-1",
    name: "Samosa",
    description: "Vegetable or Lamb",
    price: 7,
    category: "india",
    dietary: ["vegetarian"],
  },
  {
    id: "pa-in-mc-1",
    name: "Butter Chicken",
    description: "Murgh Makhani - a creamy, tangy, and sweet chicken curry",
    price: 22,
    category: "india",
    dietary: [],
    featured: true,
  },
  {
    id: "pa-in-rc-1",
    name: "Biryani",
    description: "Vegetable, Chicken, or Lamb",
    price: 19,
    category: "india",
    dietary: [],
  },

  // Malaysia & Singapore
  {
    id: "pa-my-mc-1",
    name: "Laksa",
    description: "Spicy Coconut Noodle Soup",
    price: 17,
    category: "malaysia-singapore",
    dietary: [],
    spiceLevel: 2,
  },
  {
    id: "pa-my-mc-2",
    name: "Hainanese Chicken Rice",
    description: "Poached chicken and seasoned rice, served with chili sauce",
    price: 18,
    category: "malaysia-singapore",
    dietary: [],
  },

  // Desserts
  {
    id: "pa-ds-1",
    name: "Mochi Ice Cream",
    description: "Japanese rice cake with an ice cream filling",
    price: 8,
    category: "desserts-asia",
    dietary: ["vegetarian", "gluten-free"],
  },
  {
    id: "pa-ds-2",
    name: "Mango Sticky Rice",
    description: "Classic Thai dessert with sweet sticky rice, fresh mango, and coconut milk",
    price: 10,
    category: "desserts-asia",
    dietary: ["vegetarian", "gluten-free"],
  },

  // Beverages
  {
    id: "pa-bv-1",
    name: "Thai Iced Tea",
    description: "Sweet and creamy black tea beverage",
    price: 5,
    category: "beverages-asia",
    dietary: ["vegetarian"],
  },
  {
    id: "pa-bv-2",
    name: "Mango Lassi",
    description: "A popular and traditional yogurt-based drink from India",
    price: 6,
    category: "beverages-asia",
    dietary: ["vegetarian"],
  },
  {
    id: "pa-jp-mc-2",
    name: "Sushi",
    description: "A traditional dish from Japan.",
    price: 15,
    category: "japan",
    dietary: [],
  },
  {
    id: "pa-jp-mc-3",
    name: "Ramen",
    description: "A traditional dish from Japan.",
    price: 15,
    category: "japan",
    dietary: [],
  },
  {
    id: "pa-jp-mc-4",
    name: "Tempura",
    description: "A traditional dish from Japan.",
    price: 15,
    category: "japan",
    dietary: [],
  },
  {
    id: "pa-jp-mc-5",
    name: "Kaiseki",
    description: "A traditional dish from Japan.",
    price: 15,
    category: "japan",
    dietary: [],
  },
  {
    id: "pa-kr-mc-2",
    name: "Kimchi",
    description: "A traditional dish from South Korea.",
    price: 15,
    category: "korea",
    dietary: [],
  },
  {
    id: "pa-kr-mc-3",
    name: "Samgyeopsal",
    description: "A traditional dish from South Korea.",
    price: 15,
    category: "korea",
    dietary: [],
  },
  {
    id: "pa-kr-mc-4",
    name: "Tteokbokki",
    description: "A traditional dish from South Korea.",
    price: 15,
    category: "korea",
    dietary: [],
  },
  {
    id: "pa-cn-mc-3",
    name: "Dim Sum",
    description: "A traditional dish from China.",
    price: 15,
    category: "china",
    dietary: [],
  },
  {
    id: "pa-cn-mc-4",
    name: "Mapo Tofu",
    description: "A traditional dish from China.",
    price: 15,
    category: "china",
    dietary: [],
  },
  {
    id: "pa-vn-mc-1",
    name: "Pho",
    description: "A traditional dish from Vietnam.",
    price: 15,
    category: "vietnam",
    dietary: [],
  },
  {
    id: "pa-vn-mc-2",
    name: "Banh Xeo",
    description: "A traditional dish from Vietnam.",
    price: 15,
    category: "vietnam",
    dietary: [],
  },
  {
    id: "pa-th-mc-2",
    name: "Tom Yum",
    description: "A traditional dish from Thailand.",
    price: 15,
    category: "thailand",
    dietary: [],
  },
  {
    id: "pa-th-mc-3",
    name: "Green Curry",
    description: "A traditional dish from Thailand.",
    price: 15,
    category: "thailand",
    dietary: [],
  },
  {
    id: "pa-th-mc-4",
    name: "Pad Krapow",
    description: "A traditional dish from Thailand.",
    price: 15,
    category: "thailand",
    dietary: [],
  },
  {
    id: "pa-id-mc-1",
    name: "Nasi Goreng",
    description: "A traditional dish from Indonesia.",
    price: 15,
    category: "indonesia",
    dietary: [],
  },
  {
    id: "pa-id-mc-2",
    name: "Satay",
    description: "A traditional dish from Indonesia.",
    price: 15,
    category: "indonesia",
    dietary: [],
  },
  {
    id: "pa-id-mc-3",
    name: "Rendang",
    description: "A traditional dish from Indonesia.",
    price: 15,
    category: "indonesia",
    dietary: [],
  },
  {
    id: "pa-id-mc-4",
    name: "Soto Betawi",
    description: "A traditional dish from Indonesia.",
    price: 15,
    category: "indonesia",
    dietary: [],
  },
  {
    id: "pa-my-mc-3",
    name: "Nasi Lemak",
    description: "A traditional dish from Malaysia.",
    price: 15,
    category: "malaysia",
    dietary: [],
  },
  {
    id: "pa-my-mc-4",
    name: "Roti Canai",
    description: "A traditional dish from Malaysia.",
    price: 15,
    category: "malaysia",
    dietary: [],
  },
  {
    id: "pa-my-mc-5",
    name: "Char Kway Teow",
    description: "A traditional dish from Malaysia.",
    price: 15,
    category: "malaysia",
    dietary: [],
  },
  {
    id: "pa-ph-mc-1",
    name: "Adobo",
    description: "A traditional dish from Philippines.",
    price: 15,
    category: "philippines",
    dietary: [],
  },
  {
    id: "pa-ph-mc-2",
    name: "Lechon",
    description: "A traditional dish from Philippines.",
    price: 15,
    category: "philippines",
    dietary: [],
  },
  {
    id: "pa-ph-mc-3",
    name: "Sisig",
    description: "A traditional dish from Philippines.",
    price: 15,
    category: "philippines",
    dietary: [],
  },
  {
    id: "pa-ph-mc-4",
    name: "Halo-Halo",
    description: "A traditional dish from Philippines.",
    price: 15,
    category: "philippines",
    dietary: [],
  },
  {
    id: "pa-sg-mc-1",
    name: "Chili Crab",
    description: "A traditional dish from Singapore.",
    price: 15,
    category: "singapore",
    dietary: [],
  },
  {
    id: "pa-sg-mc-2",
    name: "Kaya Toast",
    description: "A traditional dish from Singapore.",
    price: 15,
    category: "singapore",
    dietary: [],
  },
  {
    id: "pa-kh-mc-1",
    name: "Amok",
    description: "A traditional dish from Cambodia.",
    price: 15,
    category: "cambodia",
    dietary: [],
  },
  {
    id: "pa-kh-mc-2",
    name: "Lok Lak",
    description: "A traditional dish from Cambodia.",
    price: 15,
    category: "cambodia",
    dietary: [],
  },
  {
    id: "pa-kh-mc-3",
    name: "Fish Amok",
    description: "A traditional dish from Cambodia.",
    price: 15,
    category: "cambodia",
    dietary: [],
  },
  {
    id: "pa-kh-mc-4",
    name: "Kuy Teav",
    description: "A traditional dish from Cambodia.",
    price: 15,
    category: "cambodia",
    dietary: [],
  },
  {
    id: "pa-mm-mc-1",
    name: "Mohinga",
    description: "A traditional dish from Myanmar.",
    price: 15,
    category: "myanmar",
    dietary: [],
  },
  {
    id: "pa-mm-mc-2",
    name: "Laphet",
    description: "A traditional dish from Myanmar.",
    price: 15,
    category: "myanmar",
    dietary: [],
  },
  {
    id: "pa-mm-mc-3",
    name: "Shan Noodles",
    description: "A traditional dish from Myanmar.",
    price: 15,
    category: "myanmar",
    dietary: [],
  },
  {
    id: "pa-mm-mc-4",
    name: "Ohno Khao Swe",
    description: "A traditional dish from Myanmar.",
    price: 15,
    category: "myanmar",
    dietary: [],
  },
  {
    id: "pa-la-mc-1",
    name: "Laap",
    description: "A traditional dish from Laos.",
    price: 15,
    category: "laos",
    dietary: [],
  },
  {
    id: "pa-la-mc-2",
    name: "Tum Mak Hoong",
    description: "A traditional dish from Laos.",
    price: 15,
    category: "laos",
    dietary: [],
  },
  {
    id: "pa-la-mc-3",
    name: "Khao Soi",
    description: "A traditional dish from Laos.",
    price: 15,
    category: "laos",
    dietary: [],
  },
  {
    id: "pa-la-mc-4",
    name: "Sticky Rice",
    description: "A traditional dish from Laos.",
    price: 15,
    category: "laos",
    dietary: [],
  },
  {
    id: "pa-id-mc-5",
    name: "Tumpeng",
    description: "A traditional dish from Indonesia.",
    price: 15,
    category: "indonesia",
    dietary: [],
  },
  {
    id: "pa-bn-mc-1",
    name: "Ambuyat",
    description: "A traditional dish from Brunei.",
    price: 15,
    category: "brunei",
    dietary: [],
  },
  {
    id: "pa-bn-mc-2",
    name: "Nasi Katok",
    description: "A traditional dish from Brunei.",
    price: 15,
    category: "brunei",
    dietary: [],
  },
  {
    id: "pa-bn-mc-3",
    name: "Beef Rendang",
    description: "A traditional dish from Brunei.",
    price: 15,
    category: "brunei",
    dietary: [],
  },
  {
    id: "pa-in-mc-2",
    name: "Rogan Josh",
    description: "A traditional dish from India.",
    price: 15,
    category: "india",
    dietary: [],
  },
  {
    id: "pa-in-mc-3",
    name: "Masala Dosa",
    description: "A traditional dish from India.",
    price: 15,
    category: "india",
    dietary: [],
  },
  {
    id: "pa-np-mc-1",
    name: "Dal Bhat",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-2",
    name: "Momo",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-3",
    name: "Sel Roti",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-4",
    name: "Thukpa",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-pk-mc-1",
    name: "Mutton Biryani",
    description: "A traditional dish from Pakistan.",
    price: 15,
    category: "pakistan",
    dietary: [],
  },
  {
    id: "pa-pk-mc-2",
    name: "Nihari",
    description: "A traditional dish from Pakistan.",
    price: 15,
    category: "pakistan",
    dietary: [],
  },
  {
    id: "pa-pk-mc-3",
    name: "Chapli Kebab",
    description: "A traditional dish from Pakistan.",
    price: 15,
    category: "pakistan",
    dietary: [],
  },
  {
    id: "pa-pk-mc-4",
    name: "Haleem",
    description: "A traditional dish from Pakistan.",
    price: 15,
    category: "pakistan",
    dietary: [],
  },
  {
    id: "pa-lk-mc-1",
    name: "Kottu Roti",
    description: "A traditional dish from Sri Lanka.",
    price: 15,
    category: "sri-lanka",
    dietary: [],
  },
  {
    id: "pa-lk-mc-2",
    name: "Hoppers",
    description: "A traditional dish from Sri Lanka.",
    price: 15,
    category: "sri-lanka",
    dietary: [],
  },
  {
    id: "pa-lk-mc-3",
    name: "Fish Curry",
    description: "A traditional dish from Sri Lanka.",
    price: 15,
    category: "sri-lanka",
    dietary: [],
  },
  {
    id: "pa-lk-mc-4",
    name: "Pol Sambol",
    description: "A traditional dish from Sri Lanka.",
    price: 15,
    category: "sri-lanka",
    dietary: [],
  },
  {
    id: "pa-bt-mc-1",
    name: "Ema Datshi",
    description: "A traditional dish from Bhutan.",
    price: 15,
    category: "bhutan",
    dietary: [],
  },
  {
    id: "pa-bt-mc-2",
    name: "Jasha Maroo",
    description: "A traditional dish from Bhutan.",
    price: 15,
    category: "bhutan",
    dietary: [],
  },
  {
    id: "pa-bt-mc-3",
    name: "Phaksha Paa",
    description: "A traditional dish from Bhutan.",
    price: 15,
    category: "bhutan",
    dietary: [],
  },
  {
    id: "pa-ru-mc-1",
    name: "Borscht",
    description: "A traditional dish from Russia.",
    price: 15,
    category: "russia",
    dietary: [],
  },
  {
    id: "pa-ru-mc-2",
    name: "Pelmeni",
    description: "A traditional dish from Russia.",
    price: 15,
    category: "russia",
    dietary: [],
  },
  {
    id: "pa-ru-mc-3",
    name: "Blini",
    description: "A traditional dish from Russia.",
    price: 15,
    category: "russia",
    dietary: [],
  },
  {
    id: "pa-ru-mc-4",
    name: "Shashlik",
    description: "A traditional dish from Russia.",
    price: 15,
    category: "russia",
    dietary: [],
  },
  {
    id: "pa-uz-mc-1",
    name: "Plov",
    description: "A traditional dish from Uzbekistan.",
    price: 15,
    category: "uzbekistan",
    dietary: [],
  },
  {
    id: "pa-uz-mc-2",
    name: "Lagman",
    description: "A traditional dish from Uzbekistan.",
    price: 15,
    category: "uzbekistan",
    dietary: [],
  },
  {
    id: "pa-uz-mc-3",
    name: "Manti",
    description: "A traditional dish from Uzbekistan.",
    price: 15,
    category: "uzbekistan",
    dietary: [],
  },
  {
    id: "pa-uz-mc-4",
    name: "Samsa",
    description: "A traditional dish from Uzbekistan.",
    price: 15,
    category: "uzbekistan",
    dietary: [],
  },
  {
    id: "pa-sa-mc-1",
    name: "Kabsa",
    description: "A traditional dish from Saudi Arabia.",
    price: 15,
    category: "saudi-arabia",
    dietary: [],
  },
  {
    id: "pa-sa-mc-2",
    name: "Harees",
    description: "A traditional dish from Saudi Arabia.",
    price: 15,
    category: "saudi-arabia",
    dietary: [],
  },
  {
    id: "pa-sa-mc-3",
    name: "Mandi",
    description: "A traditional dish from Saudi Arabia.",
    price: 15,
    category: "saudi-arabia",
    dietary: [],
  },
  {
    id: "pa-sa-mc-4",
    name: "Mutabbaq",
    description: "A traditional dish from Saudi Arabia.",
    price: 15,
    category: "saudi-arabia",
    dietary: [],
  },
  {
    id: "pa-ir-mc-1",
    name: "Khoresht-e Ghormeh Sabzi",
    description: "A traditional dish from Iran.",
    price: 15,
    category: "iran",
    dietary: [],
  },
  {
    id: "pa-ir-mc-2",
    name: "Chelo Kebab",
    description: "A traditional dish from Iran.",
    price: 15,
    category: "iran",
    dietary: [],
  },
  {
    id: "pa-ir-mc-3",
    name: "Fesenjan",
    description: "A traditional dish from Iran.",
    price: 15,
    category: "iran",
    dietary: [],
  },
  {
    id: "pa-ir-mc-4",
    name: "Tahdig",
    description: "A traditional dish from Iran.",
    price: 15,
    category: "iran",
    dietary: [],
  },
  {
    id: "pa-lb-mc-1",
    name: "Hummus",
    description: "A traditional dish from Lebanon.",
    price: 15,
    category: "lebanon",
    dietary: [],
  },
  {
    id: "pa-lb-mc-2",
    name: "Falafel",
    description: "A traditional dish from Lebanon.",
    price: 15,
    category: "lebanon",
    dietary: [],
  },
  {
    id: "pa-lb-mc-3",
    name: "Tabbouleh",
    description: "A traditional dish from Lebanon.",
    price: 15,
    category: "lebanon",
    dietary: [],
  },
  {
    id: "pa-lb-mc-4",
    name: "Shawarma",
    description: "A traditional dish from Lebanon.",
    price: 15,
    category: "lebanon",
    dietary: [],
  },
  {
    id: "pa-sy-mc-1",
    name: "Kibbeh",
    description: "A traditional dish from Syria.",
    price: 15,
    category: "syria",
    dietary: [],
  },
  {
    id: "pa-sy-mc-2",
    name: "Fatayer",
    description: "A traditional dish from Syria.",
    price: 15,
    category: "syria",
    dietary: [],
  },
  {
    id: "pa-ye-mc-1",
    name: "Fahsa",
    description: "A traditional dish from Yemen.",
    price: 15,
    category: "yemen",
    dietary: [],
  },
  {
    id: "pa-ye-mc-2",
    name: "Saltah",
    description: "A traditional dish from Yemen.",
    price: 15,
    category: "yemen",
    dietary: [],
  },
  {
    id: "pa-jo-mc-1",
    name: "Mansaf",
    description: "A traditional dish from Jordan.",
    price: 15,
    category: "jordan",
    dietary: [],
  },
  {
    id: "pa-jo-mc-2",
    name: "Musakhan",
    description: "A traditional dish from Jordan.",
    price: 15,
    category: "jordan",
    dietary: [],
  },
  {
    id: "pa-jo-mc-3",
    name: "Maqluba",
    description: "A traditional dish from Jordan.",
    price: 15,
    category: "jordan",
    dietary: [],
  },
  {
    id: "pa-jo-mc-4",
    name: "Knafeh",
    description: "A traditional dish from Jordan.",
    price: 15,
    category: "jordan",
    dietary: [],
  },
  {
    id: "pa-mn-mc-1",
    name: "Buuz",
    description: "A traditional dish from Mongolia.",
    price: 15,
    category: "mongolia",
    dietary: [],
  },
  {
    id: "pa-mn-mc-2",
    name: "Khuushuur",
    description: "A traditional dish from Mongolia.",
    price: 15,
    category: "mongolia",
    dietary: [],
  },
  {
    id: "pa-mn-mc-3",
    name: "Tsuivan",
    description: "A traditional dish from Mongolia.",
    price: 15,
    category: "mongolia",
    dietary: [],
  },
  {
    id: "pa-mn-mc-4",
    name: "Airag",
    description: "A traditional dish from Mongolia.",
    price: 15,
    category: "mongolia",
    dietary: [],
  },
  {
    id: "pa-mn-mc-5",
    name: "Khorhog",
    description: "A traditional dish from Mongolia.",
    price: 15,
    category: "mongolia",
    dietary: [],
  },
  {
    id: "pa-af-mc-1",
    name: "Kabuli Palaw",
    description: "A traditional dish from Afghanistan.",
    price: 15,
    category: "afghanistan",
    dietary: [],
  },
  {
    id: "pa-af-mc-2",
    name: "Mantu",
    description: "A traditional dish from Afghanistan.",
    price: 15,
    category: "afghanistan",
    dietary: [],
  },
  {
    id: "pa-af-mc-3",
    name: "Qabili Palau",
    description: "A traditional dish from Afghanistan.",
    price: 15,
    category: "afghanistan",
    dietary: [],
  },
  {
    id: "pa-af-mc-4",
    name: "Bolani",
    description: "A traditional dish from Afghanistan.",
    price: 15,
    category: "afghanistan",
    dietary: [],
  },
  {
    id: "pa-tm-mc-1",
    name: "Naan",
    description: "A traditional dish from Turkmenistan.",
    price: 15,
    category: "turkmenistan",
    dietary: [],
  },
  {
    id: "pa-tj-mc-1",
    name: "Palov",
    description: "A traditional dish from Tajikistan.",
    price: 15,
    category: "tajikistan",
    dietary: [],
  },
  {
    id: "pa-tj-mc-2",
    name: "Qurutob",
    description: "A traditional dish from Tajikistan.",
    price: 15,
    category: "tajikistan",
    dietary: [],
  },
  {
    id: "pa-tj-mc-3",
    name: "Sambusa",
    description: "A traditional dish from Tajikistan.",
    price: 15,
    category: "tajikistan",
    dietary: [],
  },
  {
    id: "pa-tj-mc-4",
    name: "Shurpa",
    description: "A traditional dish from Tajikistan.",
    price: 15,
    category: "tajikistan",
    dietary: [],
  },
  {
    id: "pa-np-mc-5",
    name: "Gundruk",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-6",
    name: "Dhindo",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-7",
    name: "Chatamari",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-8",
    name: "Yomari",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-9",
    name: "Aloo Tama",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-10",
    name: "Kheer",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-11",
    name: "Juju Dhau",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-12",
    name: "Bara",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-13",
    name: "Sukuti",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-14",
    name: "Choila",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-15",
    name: "Khasi Ko Masu",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-16",
    name: "Kwati",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-17",
    name: "Sapu Mhicha",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-18",
    name: "Samay Baji",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-19",
    name: "Pustakari",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-20",
    name: "Tarkari",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-21",
    name: "Aloo Dum",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-22",
    name: "Chhoyela",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-23",
    name: "Sikarni",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-24",
    name: "Gaja",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-25",
    name: "Kinema",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-26",
    name: "Masyaura",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-27",
    name: "Phulaura",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-28",
    name: "Tama Soup",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-29",
    name: "Chiura",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
  {
    id: "pa-np-mc-30",
    name: "Haku Chhoyela",
    description: "A traditional dish from Nepal.",
    price: 15,
    category: "nepal",
    dietary: [],
  },
];
